eCommerceApp/Models/ShoppingCart.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using eCommerceApp.Areas.Identity.Data;
using eCommerceApp.Data.Base;

namespace eCommerceApp.Models
{
    public class ShoppingCart : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        // #####



        // Relationships

		// CartItem
		public List<CartItem> CartItems { get; set; }

        // AppUser
        public string? AppUserId { get; set; }
    }
}

eCommerceApp/Controllers/ProductController.cs
using eCommerceApp.Areas.Identity.Data;
using eCommerceApp.Data;
using eCommerceApp.Data.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eCommerceApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _service;

        public ProductController(UserManager<AppUser> userManager, IProductService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync(s => s.Seller);
            return View(data);
        }

        public async Task<IActionResult> Details(int id)
        {
            var productDetail = await _service.GetProductByIdAsync(id);
            return View(productDetail);
        }
    }
}

eCommerceApp/Controllers/SellerController.cs
using eCommerceApp.Data;
using eCommerceApp.Data.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eCommerceApp.Controllers
{
    public class SellerController : Controller
    {
        private readonly ISellerService _service;

        public SellerController(ISellerService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync(p => p.Products);
            return View(data);
        }

		public async Task<IActionResult> Details(int id)
		{
			var sellerDetail = await _service.GetSellerByIdAsync(id);
			return View(sellerDetail);
		}
	}
}

eCommerceApp/Controllers/ShoppingCartController.cs
using System.Security.Claims;
using eCommerceApp.Areas.Identity.Data;
using eCommerceApp.Data;
using eCommerceApp.Data.Services;
using eCommerceApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace eCommerceApp.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartService _service;
        private readonly UserManager<AppUser> _userManager;
        private readonly AuthDbContext _authDbContext;
        private readonly AppDbContext _appDbContext;

        public ShoppingCartController(IShoppingCartService service,
                                        UserManager<AppUser> userManager, 
                                        AuthDbContext authDbContext, 
                                        AppDbContext appDbContext)
        {
            _service = service;
            this._userManager = userManager;
            _authDbContext = authDbContext;
            _appDbContext = appDbContext;
        }

        public async Task<IActionResult> Index() 
        {
            var userId = _userManager.GetUserId(this.User);

            var shoppingCart = await _appDbContext.ShoppingCarts.FirstOrDefaultAsync(cart => cart.AppUserId == userId);

            if (shoppingCart == null)
            {
                shoppingCart = new ShoppingCart
                {
                    AppUserId = userId
                };

                _appDbContext.ShoppingCarts.Add(shoppingCart);
                await _appDbContext.SaveChangesAsync();
            }

            ViewData["UserId"] = userId;

            var data = await _service.GetAllAsync(c => c.CartItems);
			return View(data);
        }

        public async Task<IActionResult> Details(string id)
        {
            var shoppingCartDetail = await _service.GetShoppingCartByIdAsync(id);
            return View(shoppingCartDetail);
        }

        public async Task<IActionResult> CreateUserCart()
        {
            var userId = _userManager.GetUserId(this.User);

            var shoppingCart = await _appDbContext.ShoppingCarts.FirstOrDefaultAsync(cart => cart.AppUserId == userId);

            if (shoppingCart == null)
            {
                shoppingCart = new ShoppingCart
                {
                    AppUserId = userId
                };

                _appDbContext.ShoppingCarts.Add(shoppingCart);
                await _appDbContext.SaveChangesAsync();
            }

            ViewData["UserId"] = userId;

            return View();
        }

        public async Task<IActionResult> AddToCart(int id)
        {
            var userId = _userManager.GetUserId(this.User);

            var shoppingCart = await _appDbContext.ShoppingCarts.FirstOrDefaultAsync(cart => cart.AppUserId == userId);

            if (shoppingCart == null)
            {
                shoppingCart = new ShoppingCart
                {
                    AppUserId = userId
                };

                _appDbContext.ShoppingCarts.Add(shoppingCart);
                await _appDbContext.SaveChangesAsync();
            }

            ViewData["UserId"] = userId;


            var shoppingCartId = _service.GetShoppingCartIdByUserId(userId);

            var cartItem = await _appDbContext.CartItems.FirstOrDefaultAsync(cart => cart.ShoppingCartId == shoppingCartId);

            if (shoppingCartId != null)
            {
                var existingCartItem = await _appDbContext.CartItems.FirstOrDefaultAsync(item => item.ProductId == id && item.ShoppingCartId == shoppingCartId);

                if (existingCartItem != null)
                {
                    existingCartItem.Quantity += 1;
                }
                else
                {
                    cartItem = new CartItem
                    {
                        ShoppingCartId = shoppingCartId,
                        ProductId = id,
                        Quantity = 1
                    };
                    _appDbContext.CartItems.Add(cartItem);
                }
                
                await _appDbContext.SaveChangesAsync();
            }

            return Redirect(Request.Headers["Referer"].ToString());
        }

        public async Task<IActionResult> EmptyShoppingCart(string id)
        {
            var userId = _userManager.GetUserId(this.User);

            var shoppingCart = await _appDbContext.ShoppingCarts
                .Include(cart => cart.CartItems)
                .FirstOrDefaultAsync(cart => cart.AppUserId == userId);

            if (shoppingCart != null)
            {
                _appDbContext.CartItems.RemoveRange(shoppingCart.CartItems); // Remove all CartItems
                await _appDbContext.SaveChangesAsync();

                _appDbContext.ShoppingCarts.Remove(shoppingCart); // Remove the Shopping Cart itself
                await _appDbContext.SaveChangesAsync();
            }

            return Redirect(Request.Headers["Referer"].ToString());
        }

        public async Task<IActionResult> Increase(int id)
        {
            var userId = _userManager.GetUserId(this.User);

            var shoppingCart = await _appDbContext.ShoppingCarts.FirstOrDefaultAsync(cart => cart.AppUserId == userId);

            var shoppingCartId = _service.GetShoppingCartIdByUserId(userId);

            var cartItem = await _appDbContext.CartItems.FirstOrDefaultAsync(cart => cart.ShoppingCartId == shoppingCartId);

            if (shoppingCartId != null)
            {
                var existingCartItem = await _appDbContext.CartItems.FirstOrDefaultAsync(item => item.ProductId == id && item.ShoppingCartId == shoppingCartId);

                if (existingCartItem != null)
                {
                    existingCartItem.Quantity += 1;
                }

                await _appDbContext.SaveChangesAsync();
            }

            return Redirect(Request.Headers["Referer"].ToString());
        }

        public async Task<IActionResult> Decrease(int id)
        {
            var userId = _userManager.GetUserId(this.User);

            var shoppingCart = await _appDbContext.ShoppingCarts.FirstOrDefaultAsync(cart => cart.AppUserId == userId);

            var shoppingCartId = _service.GetShoppingCartIdByUserId(userId);

            var cartItem = await _appDbContext.CartItems.FirstOrDefaultAsync(cart => cart.ShoppingCartId == shoppingCartId);

            if (shoppingCartId != null)
            {
                var existingCartItem = await _appDbContext.CartItems.FirstOrDefaultAsync(item => item.ProductId == id && item.ShoppingCartId == shoppingCartId);

                if (existingCartItem != null)
                {
                    existingCartItem.Quantity -= 1;

                    if (existingCartItem.Quantity == 0)
                    {
                        _appDbContext.CartItems.Remove(existingCartItem);
                    }
                }

                await _appDbContext.SaveChangesAsync();
            }

            return Redirect(Request.Headers["Referer"].ToString());
        }

        public async Task<IActionResult> DeleteItem(int id)
        {
            var userId = _userManager.GetUserId(this.User);

            var shoppingCartId = _service.GetShoppingCartIdByUserId(userId);

            if (shoppingCartId != null)
            {
                var existingCartItem = await _appDbContext.CartItems.FirstOrDefaultAsync(item => item.ProductId == id && item.ShoppingCartId == shoppingCartId);

                if (existingCartItem != null)
                {
                    existingCartItem.Quantity = 0;

                    if (existingCartItem.Quantity == 0)
                    {
                        _appDbContext.CartItems.Remove(existingCartItem);
                    }

                    await _appDbContext.SaveChangesAsync();
                }
            }

            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

eCommerceApp/Views/ShoppingCart/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@using eCommerceApp.Areas.Identity.Data;
@using eCommerceApp.Data.Services
@using eCommerceApp.Data;
@using Microsoft.EntityFrameworkCore;
@inject IProductService ProductService
@inject IShoppingCartService ShoppingCartService
@inject UserManager<AppUser> userManager
@inject AppDbContext appDbContext
@model IEnumerable<ShoppingCart>
@{
    decimal totalProductPrice = 0;
    decimal ShipmentPrice = 5;
    decimal totalPrice = 0;
    var userId = userManager.GetUserId(this.User);
    var userShoppingCart = ShoppingCartService.GetShoppingCartIdByUserId(userId);

    var shoppingCart = await appDbContext.ShoppingCarts
    .Where(item => item.AppUserId == userId)
    .ToListAsync();

    var cartItems = await appDbContext.CartItems
    .Where(item => item.ShoppingCartId == userShoppingCart)
    .ToListAsync();
}

<style>
    .cart-img {
        height: 150px;
        max-width: 100px;
        object-fit: cover;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <table class="table">
                <thead>
                    <tr class="text-left">
                        <th class="text-center">ürün görsel</th>
                        <th class="text-center">ürün satıcı</th>
                        <th class="text-center">ürün isim</th>
                        <th class="text-center">ürün fiyat</th>
                        <th class="text-center">ürün adet</th>
                        <th class="text-center">eylemler</th>
                    </tr>
                </thead>
                <tbody>



                    @foreach (var item in shoppingCart)
                    {
                        foreach (var cartItem in cartItems)
                        {
                            var product = await ProductService.GetProductByIdAsync(cartItem.ProductId);

                            if (product != null)
                            {
                                <tr>
                                    <td class="text-center align-middle">
                                        <a class="text-decoration-none text-black" asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">
                                            <img class="cart-img" src="/@product.Image" />
                                        </a>
                                    </td>
                                    <td class="text-center align-middle">
                                        <a class="text-decoration-none text-black" asp-controller="Seller" asp-action="Details" asp-route-id="@product.Seller.Id">
                                            @product.Seller.Name
                                        </a>
                                    </td>
                                    <td class="text-center align-middle">
                                        <a class="text-decoration-none text-black" asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">
                                            @product.Name
                                        </a>
                                    </td>
                                    <td class="text-center align-middle">@product.Price $</td>
                                    <td class="text-center align-middle">@cartItem.Quantity</td>
                                    <td class="text-center align-middle">
                                        <a class="btn btn-sm bg-success text-light" asp-controller="ShoppingCart" asp-action="Increase" asp-route-id="@product.Id">+</a>
                                        <a class="btn btn-sm bg-danger text-light" asp-controller="ShoppingCart" asp-action="DeleteItem" asp-route-id="@product.Id">
                                            <img class="align-middle" src="/icon/trash_icon.png" style="width: 20px; height: 20px;">
                                        </a>
                                        <a class="btn btn-sm bg-secondary text-light" asp-controller="ShoppingCart" asp-action="Decrease" asp-route-id="@product.Id">-</a>
                                    </td>

                                </tr>
                                totalProductPrice += (decimal)product.Price * cartItem.Quantity;
                            }
                        }
                    }

                </tbody>
            </table>
        </div>
        <div class="col-md-4 order-first order-md-last">
            <div class="content">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Sipariş Özeti</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Ürünlerin Toplamı: @totalProductPrice $</li>
                        <li class="list-group-item">Kargo Toplamı: @ShipmentPrice $</li>
                        @{
                            totalPrice += (decimal)totalProductPrice + (decimal)ShipmentPrice;
                        }
                        <li class="list-group-item">Toplam: @totalPrice $</li>
                    </ul>
                    <div class="card-body">
                        <a class="text-decoration-none text-black" asp-controller="ShoppingCart" asp-action="EmptyShoppingCart" asp-route-id="userId">Sepeti Onayla</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>